### PR TITLE
Updates Cake-components to 1.0, updated readme to refer to github discussions

### LINKED ISSUE #48: Update to Cake(.Issues) 1.0

### LINKED ISSUE #54: Migrate from deprecated FxCop analyzers to .NET analyzers
https://github.com/dotnet/roslyn-analyzers/releases/tag/v3.3.2

New deprecation warning CA9998 for Microsoft.CodeAnalysis.FxCopAnalyzers package:
FxCopAnalyzers package has been deprecated in favor of 'Microsoft.CodeAnalysis.NetAnalyzers', that ships with the .NET SDK. Please refer to https://docs.microsoft.com/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers to migrate to .NET analyzers.

### LINKED ISSUE #58: Replace Gitter with GitHub Discussions
The Discussion platform for Cake-Contrib has been moved from Gitter to GitHub Discussion (see cake-build/website#1470). 
Please check this repo for references to Gitte and replace them accordingly.

Search suggests that references could be in

 - README.md

### PR DESCRIPTION
**Pull request by janniksam**
Resolves #48
Resolves #54 
Resolves #58

### CODE REVIEW

**Comment by janniksam** [comment]
@eoehen I closed your PR because I have already done it here (didn't see until now)

**Comment by janniksam** [comment]
This PR waits for Cake.Issues 1.0

**Review by eoehen — APPROVED** [review]

**Review by eoehen — CHANGES_REQUESTED** [review]
Waiting for updating Cake.Issues 1.0. Sorry, I have overlooked it.

**Comment by pascalberger** [comment]
> This PR waits for Cake.Issues 1.0

Cake.Issues 1.0 Beta 1 is now available. I'm now waiting for all addins to be prepared for update and then we can release 1.0 RTM.

**Comment by janniksam** [comment]
Okay, let me change the reference this afternoon. I doubt that anything broke with the new version, hopefully this will be an easy update. 👍

**Comment by janniksam** [comment]
I updated the references now :)

@pascalberger So, you want me to release merge this and work on a 1.0 beta release before the final release?

**Review by eoehen — APPROVED** [review]

**Review by pascalberger — APPROVED** [review]
LGTM

**Pull request merged**
